[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
user=root

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
priority=999
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm-error.log

[program:migrations]
command=bash -c "/usr/bin/wait-for-it database:3306 -- bin/console doctrine:migrations:migrate"
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/var/log/supervisor/migrations.log
stderr_logfile=/var/log/supervisor/migrations-error.log
